Repository wecode-bootcamp-korea/14-1st-Gotchapedia-backend, pull requests merged in 2020-11, with the labels that each got.

#3 ADD: models.py 작성 완료
  .DS_Store
  analysis/__init__.py
  analysis/admin.py
  analysis/apps.py
  analysis/migrations/0001_initial.py
  analysis/migrations/0002_auto_20201117_0725.py
  analysis/migrations/0003_auto_20201118_0728.py
  analysis/migrations/__init__.py
  analysis/models.py
  analysis/tests.py
  analysis/views.py
  comment/__init__.py
  comment/admin.py
  comment/apps.py
  comment/migrations/0001_initial.py
  comment/migrations/0002_auto_20201118_0728.py
  comment/migrations/__init__.py
  comment/models.py
  comment/tests.py
  comment/views.py
  movie/__init__.py
  movie/admin.py
  movie/apps.py
  movie/migrations/0001_initial.py
  movie/migrations/0002_auto_20201117_0604.py
  movie/migrations/0003_auto_20201117_0613.py
  movie/migrations/0004_auto_20201118_0728.py
  movie/migrations/__init__.py
  movie/models.py
  movie/tests.py
  movie/views.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20201117_0644.py
  users/migrations/0003_auto_20201117_0725.py
  users/models.py
  watcha/settings.py
Labels: Status: 리뷰 요청

#4 회원가입, 로그인 기능 추가
  analysis/migrations/0004_auto_20201119_0608.py
  movie/migrations/0005_auto_20201119_0608.py
  movie/models.py
  users/urls.py
  users/utils.py
  users/views.py
  watcha/urls.py
Labels: Status: Accepted

#6 MODIFY: views.py 별점 RESTful API형식 CRUD 구현 및 수정
  analysis/urls.py
  analysis/views.py
  movie/migrations/0005_auto_20201119_0640.py
  movie/urls.py
  watcha/urls.py
Labels: Status: Accepted, Status: 리뷰 요청

#8 ADD: analysis views.py 추가
  analysis/.DS_Store
  analysis/migrations/.DS_Store
  analysis/migrations/0001_initial.py
  analysis/migrations/0002_auto_20201117_0725.py
  analysis/migrations/0003_auto_20201118_0728.py
  analysis/migrations/0004_auto_20201119_0608.py
  analysis/urls.py
  analysis/views.py
  comment/migrations/0004_remove_comment_content.py
  users/utils.py
  watcha/settings.py
Labels: Status: 컨플릭트 해결 요청

#9 ADD: movie app 영화 정보 출력을 위한 view 작성, url 수정
  movie/urls.py
  movie/views.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#10 ADD: 선호 장르/국가 기능 추가
  analysis/urls.py
  analysis/views.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#12 ADD: 영화 상세 정보 조회 구현
  movie/urls.py
  movie/views.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#13 MODIFY: searchview.py 수정
  movie/.DS_Store
  movie/migrations/.DS_Store
  movie/migrations/0006_auto_20201121_1143.py
  movie/migrations/0007_auto_20201121_1151.py
  movie/models.py
  movie/urls.py
  movie/views.py
  users/views.py
Labels: Status: 리뷰 요청

#14 ADD: 댓글 CRUD를 위한 commentview 추가, url 추가
  comment/urls.py
  comment/views.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#15 ADD: 코멘트 좋아요 기능 구현을 위한 commentlikeview 구현, url 추가
  comment/urls.py
  comment/views.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#17 ADD: interest(보고싶어요, 보는중 기능) view 추가
  movie/urls.py
  movie/views.py
Labels: Status: 리뷰 요청

#18 ADD: userviews.py 추가
  users/views.py
Labels: Status: 리뷰 요청

#19 ADD: 코멘트 리스트 구현을 위한 view, url 작성
  comment/urls.py
  comment/views.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#20 ADD: 대댓글 기능 CRUD
  comment/urls.py
  comment/views.py
Labels: Status: 리뷰 요청

#23 MODIFY : CommentView url 및 view 수정 / StarView 오타 수정
  analysis/views.py
  comment/urls.py
  comment/views.py
Labels: Status: 리뷰 요청

#24 MODIFY : RESTful API 형식으로 URL 수정
  .DS_Store
  analysis/.DS_Store
  analysis/migrations/0001_initial.py
  analysis/urls.py
  comment/.DS_Store
  comment/__init__.py
  comment/admin.py
  comment/apps.py
  comment/migrations/.DS_Store
  comment/migrations/0001_initial.py
  comment/migrations/__init__.py
  comment/models.py
  comment/tests.py
  comment/urls.py
  comment/views.py
  movie/.DS_Store
  movie/migrations/0001_initial.py
  movie/models.py
  movie/urls.py
  movie/views.py
  users/.DS_Store
  users/migrations/0001_initial.py
  watcha/.DS_Store
  watcha/settings.py
  watcha/urls.py
Labels: Status: 리뷰 요청

#25 MODIFY: CommentListView 수정
  analysis/urls.py
  movie/views.py
Labels: Status: 리뷰 요청
